### ISSUE TITLE
Change the colors using CSS

### ISSUE THREAD

**Issue by jsug9** [Retky/Mv-AwesomeBooks#4]
https://github.com/Retky/Mv-AwesomeBooks/blob/ad7e4198a811a2db2eb308eb47799e6ad0e178cc/script.js#L75

I advise you to use CSS instead of JS to change the colors of odd lines, so that it updates in real time when you remove an object. You can use 'nth-child'. Something like this:
```
.(name of your container):nth-child(odd) {
  background: (The color you want) ;
}
```

**Comment by memelopez** [comment]
Hi @Retky 👋  you're code looks awesome books! 😋 I just have a suggestion for you: 

https://github.com/Retky/Mv-AwesomeBooks/blob/ad7e4198a811a2db2eb308eb47799e6ad0e178cc/script.js#L100

you can also use the 'submit' event on the form HTML element to add a new book 📕

`document.querySelector('#form').addEventListener('submit', (e) => {});`
