### ISSUE TITLE
P2P code review - march 22

### ISSUE THREAD

**Issue by memelopez** [Retky/Mv-AwesomeBooks#6]
Hi Retky 👋  good job with the project! It works fine 💯 a simple suggestion for you is this: 

https://github.com/Retky/Mv-AwesomeBooks/blob/fdd154eccaf1f0705d451997c81120aa37b6bd52/js/modules/clearBooks.mjs#L3

an easy way to reset the list is to say: 

`list.innerHTML = '';`

have a nice day bro! 🙂

**Comment by TesheMaximillan** [comment]
It's clear and well-arranged
